/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"

CLIENT *clnt;

char *concat(char *str1, char *str2) {
	reponse *resultat;
	data parametre;
	parametre.arg1 = str1;
	parametre.arg2 = str2;
	resultat = calcul_my_strcat_1(&parametre, clnt);
	return resultat->concat;
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clnt = clnt_create(host, CALCUL, VERSION_UN, "tcp");

	char str1[32];
	fgets(str1, 32, stdin);
	char *pos1 = strchr(str1, '\n');
	*pos1 = '\0';

	char str2[32];
	fgets(str2, 32, stdin);
	char *pos2 = strchr(str2, '\n');
	*pos1 = '\0';

	printf("Mot = %s\n", concat(str1, str2));
	exit (0);
}
